# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digestapi', '0003_remove_book_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
